"""Alger protocol response codes."""

CODE_LOGIN_OK = 200
CODE_LOGIN_UNKNOWN = 300
CODE_USER_DATA = 201
CODE_USER_DATA_ERROR = 301
CODE_PIPELINE_FULL = 202
CODE_PIPELINE_FULL_ERROR = 302
CODE_EXECUTION_FROM_DB_OK = 203
CODE_EXECUTION_FROM_DB_ERROR = 303
CODE_EXECUTION_FROM_PAYLOAD_OK = 204
CODE_EXECUTION_FROM_PAYLOAD_ERROR = 304
CODE_STATUS_UPDATE_OK = 205
CODE_STATUS_UPDATE_ERROR = 305
CODE_STOP_EXECUTION_OK = 206
CODE_STOP_EXECUTION_ERROR = 306
CODE_PIPELINE_FINISHED_OK = 207
CODE_PIPELINE_FINISHED_ERROR = 307
CODE_MESSAGE_ID_ERROR = 395
CODE_UNKNOWN_TYPE = 396
CODE_TOO_MANY_EXECUTIONS = 397
CODE_EXECUTIONS_HALTED = 398
CODE_MAINTENANCE_MODE = 399
